[project]
name = "hippo_nclic_veryl"
version = "0.1.0"
[build]
source = "src"
target = { type = "directory", path = "target" }
exclude_std = true
[test]
waveform_target = { type = "directory", path = "waveforms/" }
